services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - finance_net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "finance_user", "-d", "finance_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://finance_user:finance_password@db:5432/finance_db
      - JWT_SECRET=your-super-secret-key-here
      - JWT_EXPIRES_IN=86400
    networks:
      - finance_net
    command: sh -c "npx prisma generate && ts-node-dev --respawn --transpile-only src/index.ts"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000/v1/api
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true # Better hot reloading in Docker
    depends_on:
      - backend
    networks:
      - finance_net

volumes:
  postgres_data:
  frontend_node_modules:


networks:
  finance_net:
    driver: bridge
